amcl:

  ros__parameters:

    use_map_topic: true

    base_frame_id: base_link

    odom_frame_id: odom

    scan_topic: /X2_a/front_laser/scan

    robot_model_type: differential
 
map_server:

  ros__parameters:

    yaml_filename: map.yaml
 
planner_server:

  ros__parameters:

    expected_planner_frequency: 1.0

    planner_plugins: ["GridBased"]

    GridBased:

      plugin: "nav2_navfn_planner/NavfnPlanner"
 
controller_server:

  ros__parameters:

    controller_frequency: 10.0

    controller_plugins: ["FollowPath"]

    FollowPath:

      plugin: "dwb_core::DWBLocalPlanner"
 
bt_navigator:

  ros__parameters:

    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
 
waypoint_follower:

  ros__parameters:

    loop_rate: 1.0
 
recoveries_server:

  ros__parameters:

    recovery_plugins: ["Spin", "BackUp", "Wait"]

    Spin:

      plugin: "nav2_recoveries/Spin"

    BackUp:

      plugin: "nav2_recoveries/BackUp"

    Wait:

      plugin: "nav2_recoveries/Wait"
 
local_costmap:

  ros__parameters:

    global_frame: odom

    robot_base_frame: base_link

    rolling_window: true

    resolution: 0.05

    width: 3

    height: 3

    plugins: ["voxel_layer", "inflation_layer"]

    voxel_layer:

      plugin: "nav2_costmap_2d::VoxelLayer"

    inflation_layer:

      plugin: "nav2_costmap_2d::InflationLayer"
 
global_costmap:

  ros__parameters:

    global_frame: map

    robot_base_frame: base_link

    resolution: 0.05

    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:

      plugin: "nav2_costmap_2d::StaticLayer"

    obstacle_layer:

      plugin: "nav2_costmap_2d::ObstacleLayer"

    inflation_layer:

      plugin: "nav2_costmap_2d::InflationLayer"

 
